# 🐳 Docker 이미지 자동 빌드 및 푸시
# main 브랜치에 푸시될 때마다 Docker Hub에 이미지를 자동으로 푸시합니다

name: Docker Build and Push

# 언제 실행할지 정의
on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  workflow_dispatch: # 수동 실행 가능

# 환경 변수
env:
  REGISTRY: docker.io
  IMAGE_NAME: github-actions-demo

jobs:
  # Docker 이미지 빌드 및 푸시
  build-and-push:
    name: Docker 빌드 및 푸시
    runs-on: ubuntu-latest
    
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v4
      
    - name: Docker Hub 로그인
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: 메타데이터 추출
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=latest,enable={{is_default_branch}}
          
    - name: Docker 빌드 및 푸시
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
        
    - name: Docker 빌드 및 푸시 (개발용)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.dev
        push: true
        tags: ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:dev
        labels: ${{ steps.meta.outputs.labels }}
        
        
    - name: Docker 빌드 및 푸시 (테스트용)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.test
        push: true
        tags: ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:test
        labels: ${{ steps.meta.outputs.labels }}
        
    - name: Docker 빌드 및 푸시 (멀티스테이지)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.multistage
        push: true
        tags: ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:multistage
        labels: ${{ steps.meta.outputs.labels }}
        
    - name: 이미지 정보 출력
      run: |
        echo "✅ Docker 이미지가 성공적으로 빌드되고 푸시되었습니다!"
        echo "📦 이미지 태그: ${{ steps.meta.outputs.tags }}"
        echo "🔗 Docker Hub: https://hub.docker.com/r/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}"